apiVersion: apps/v1
kind: Deployment

metadata:
  name: scraper-malt-deployment
  namespace: mongo-namespace
  labels:
    app: scraper

spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper
  template:
    metadata:
      labels:
        app: scraper
    spec:
      containers:
        - name: scraper-malt
          image: swanndolia/scraper-malt:latest
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
          resources:
            limits:
              memory: "2048Mi"
              cpu: "500m"
          env:                                       
            - name: SC_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:                         # provient des "secrets"
                  name: mongo-secret
                  key: mongo_username
            - name: SC_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo_password
            - name: SC_CONFIG_MONGODB_SERVER
              valueFrom:
                configMapKeyRef:                       # provient d'un ConfigMap
                  name: mongo-configmap
                  key: mongo_url
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory


