FROM selenium/standalone-chrome

USER root

WORKDIR /scrap-malt

COPY . .

RUN apt-get update && apt-get install python3-distutils xvfb chromium-browser -y
RUN wget https://bootstrap.pypa.io/get-pip.py
RUN python3 get-pip.py
RUN python3 -m pip install -r requirements.txt

CMD ["python3", "__main__.py"]
